Repository JAM-Productions/malker, pull requests merged in 2024-03, with the labels that each got.

#106 Adding export/import token option
  src/components/Header.jsx
  src/components/token/TokenDialog.jsx
  src/comutils.js
Labels: Frontend

#105 Using HashRouter to fix URL's bug
  src/App.jsx
  src/components/plan/PlanForm.jsx
Labels: bug, Frontend

#107 Optimize images using WEBP
  index.html
  public/jam.png
  public/jam.webp
  public/malker.jpeg
  public/malker.png
  public/malker.webp
  public/vite.svg
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/user/UserCard.jsx
Labels: Frontend

#115 Share button on planview
  src/components/dropdown/DropdownPlan.jsx
Labels: Frontend

#116 My plans
  backend/app.py
  backend/resources/plan.py
  backend/tests/functional/test_plan.py
  src/App.jsx
  src/components/plan/MyPlans.jsx
  src/components/plans/Plan.jsx
  src/comutils.js
Labels: Fullstack

#119 Update Loader
  src/components/loader/Loader.jsx
  src/components/plan/PlanForm.jsx
  src/components/plan/PlanView.jsx
Labels: Frontend

#123 Fix error deployment
  src/components/plan/MyPlans.jsx
  src/components/plan/PlanForm.jsx
  src/components/plan/PlanView.jsx
Labels: bug, Frontend

#128 Abstract `getAuthConfig`
  src/comutils.js
Labels: Frontend

#129 Plan route refactor
  src/App.jsx
  src/components/plan/PlanForm.jsx
  src/components/plans/Plan.jsx
  src/comutils.js
Labels: Frontend

#130 Add description length
  src/components/dropdown/DropdownPlan.jsx
Labels: Frontend

#131 Loading view
  src/components/dropdown/DropdownPlan.jsx
  src/components/loader/LoadingView.jsx
  src/components/plan/PlanForm.jsx
  src/components/plan/PlanView.jsx
Labels: bug, Frontend

#133 Formatting with prettier
  .prettierrc
  package-lock.json
  package.json
  src/App.jsx
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/dropdown/DropdownPlan.jsx
  src/components/form/BigInput.jsx
  src/components/form/Input.jsx
  src/components/loader/Loader.jsx
  src/components/loader/LoadingView.jsx
  src/components/navigation/BackButton.jsx
  src/components/plan/MyPlans.jsx
  src/components/plan/PlanForm.jsx
  src/components/plan/PlanView.jsx
  src/components/plans/Plan.jsx
  src/components/token/TokenDialog.jsx
  src/components/user/UserCard.jsx
  src/comutils.js
  src/config/constants.js
  src/main.jsx
Labels: Frontend

#135 Check token
  backend/app.py
  backend/resources/user.py
  backend/tests/functional/test_user.py
  src/components/token/TokenDialog.jsx
  src/comutils.js
Labels: Fullstack

#136 Update icon back button
  src/components/navigation/BackButton.jsx
Labels: Frontend

#141 Fix dependencies
  package-lock.json
  package.json
Labels: Frontend

#142 Navbar
  src/components/Header.jsx
  src/components/navigation/NavBar.jsx
Labels: Frontend

#143 Endpoints connection
  backend/resources/participants.py
  src/components/dropdown/DropdownPlan.jsx
  src/components/navigation/BackButton.jsx
  src/components/plan/PlanView.jsx
  src/components/user/UserCard.jsx
Labels: Fullstack

#145 Endpoint connection 2
  src/components/plan/PlanForm.jsx
Labels: Frontend

#147 Calendar bugs
  src/components/add-to-calendar/AddToCalendar.jsx
Labels: Bug

#164 Check prettier
  .github/workflows/prettier.yml
  package.json
Labels: DevOps

#163 Python format
  .github/workflows/autopep8.yml
  Makefile
  README.md
  backend/app.py
  backend/models/plan.py
  backend/models/user.py
  backend/requirements.txt
  backend/resources/login.py
  backend/resources/plan.py
  backend/resources/user.py
  backend/tests/conftest.py
  backend/tests/functional/test_login.py
  backend/tests/functional/test_plan.py
  backend/tests/functional/test_status.py
  backend/tests/functional/test_user.py
  backend/tests/unit/test_plan.py
  backend/tests/unit/test_user.py
Labels: DevOps, Backend

#166 Fix Python version CI
  .github/workflows/cypress.yml
  .github/workflows/flask.yml
Labels: DevOps
